import { Approval, Person } from "./types";

export const initialPeople: Person[] = [
  {
    id: "p1",
    name: "Mert A.",
    status: "Aktif",
    role: "Güreşçi",
    creative: "Ege",
    lastActivity: "2 gün önce",
    lastActivityDays: 2,
    contribution: "Yüksek",
    note: "Promo ve toplantı düzenli.",
  },
  {
    id: "p2",
    name: "Kerem D.",
    status: "Geri Dönüş",
    role: "Güreşçi",
    creative: "Deniz",
    lastActivity: "74 gün önce",
    lastActivityDays: 74,
    contribution: "Yüksek",
    note: "Geçmişte aktifti, son aylarda sessiz.",
  },
  {
    id: "p3",
    name: "Ömer F.",
    status: "Gelişim",
    role: "Güreşçi",
    creative: "Ege",
    lastActivity: "31 gün önce",
    lastActivityDays: 31,
    contribution: "Orta",
    note: "Karakter çalışması başladı.",
  },
  {
    id: "p4",
    name: "Mehmet K.",
    status: "Yeni Aday",
    role: "Güreşçi",
    lastActivity: "Bugün",
    lastActivityDays: 0,
    contribution: "Yeni",
    note: "Daha önce wrestling eğitimi almamış.",
  },
  {
    id: "p5",
    name: "Bora T.",
    status: "Beklemede",
    role: "Güreşçi",
    lastActivity: "46 gün önce",
    lastActivityDays: 46,
    contribution: "Orta",
    note: "Şehir dışında olduğu için ara verdi.",
  },
  {
    id: "p6",
    name: "Can Y.",
    status: "Aday Havuzu",
    role: "Güreşçi",
    lastActivity: "112 gün önce",
    lastActivityDays: 112,
    contribution: "Düşük",
    note: "İlgisi var, henüz somut katkı yok.",
  },
];

export const initialApprovals: Approval[] = [
  {
    id: "a1",
    personId: "p2",
    title: "Geri dönüş yoklaması",
    reason: "74 gündür aktivite yok fakat geçmiş katkısı yüksek.",
    recommendation: "Geri Dönüş",
    actionLabel: "Dönüş mesajı hazırla",
    risk: "Düşük",
  },
  {
    id: "a2",
    personId: "p4",
    title: "Yeni aday başvurusu",
    reason: "Deneyimi yok, düzenli eğitime katılabileceğini belirtti.",
    recommendation: "Yeni Aday",
    actionLabel: "Başlangıç programına al",
    risk: "Düşük",
  },
  {
    id: "a3",
    personId: "p6",
    title: "Statü kontrolü",
    reason: "112 gündür aktivite yok ve henüz somut çalışma bulunmuyor.",
    recommendation: "Aday Havuzu",
    actionLabel: "Havuzda tut",
    risk: "Orta",
  },
];
